### ISSUE TITLE
"/tmp/als_readme.md"的映射目录怎么写

### ISSUE THREAD

**Issue by Netflixxp** [wikihost-opensource/als#15]
今天看到大佬更新了，如果只写一句话，我明白是用`SPONSOR_MESSAGE=xxx`
我也看见可以用"/tmp/als_readme.md"来进行更多内容的补充，
我的理解是我在服务器上传"/tmp/als_readme.md"文件
但docker容器目录映射不是太会，希望有个说明

**Comment by samlm0** [comment]
参见: https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only

**Comment by Netflixxp** [comment]
大佬，我根据你的提示，做了如下操作
1.上传编辑好的als_readme.md到机器的tpm目录下。
然后执行docker启动`docker run -dit -e SPONSOR_MESSAGE=/tmp/als_readme.md -v /tmp:/tmp -w /tmp --name looking-glass --restart always --network host wikihostinc/looking-glass-server`
启动后，能短时间看见我的als_readme.md里面的内容，但过一会，就页面显示loading了，再过一会就打不开了，请问是指令不对吗？
