### ISSUE TITLE
[BUG] SPONSOR_MESSAGE使用/tmp/als_readme.md报错

### ISSUE THREAD

**Issue by Netflixxp** [wikihost-opensource/als#16]
BUG 
上传编辑好的als_readme.md到机器的tpm目录下。
然后执行`docker启动docker run -dit -e SPONSOR_MESSAGE=/tmp/als_readme.md -v /tmp:/tmp -w /tmp --name looking-glass --restart always --network host wikihostinc/looking-glass-server
`
docker日志报错
```
PHP Warning:  rename(/GeoLite2-City.mmdb,/app/ip.mmdb): No such file or directory in /app/components/98-uncompress-ipdb.php on line 22
PHP Fatal error:  Uncaught InvalidArgumentException: The file "/app/ip.mmdb" does not exist or is not readable. in /app/components/98-uncompress-ipdb.php:23
```

# 环境
操作系统 & Docker 版本 (`lsb_release -a` && `docker version`):

使用的镜像版本 (`docker ps | grep als`):

# 现象
预期返回:
```
这样这样这样
```
实际返回:
```
那样那样那样
```

**Comment by samlm0** [comment]
更换工作目录导致, 且映射 /tmp 是非常危险的

建议新建一个目录, 如 /opt/tHe_DaTa

然后放置 /opt/tHe_DaTa/readme.md
```
docker run -dit -e SPONSOR_MESSAGE=/tmp/readme.md -v /opt/tHe_DaTa/readme.md:/tmp/readme.md --name looking-glass --restart always --network host wikihostinc/looking-glass-server
```

**Comment by samlm0** [comment]
不是程序 BUG 导致的问题, 关闭 issue
