### ISSUE TITLE
测速建议两种模式，单线程和多线程，这样大家就能更真实的了解网络水平

### ISSUE THREAD

**Issue by applesense** [wikihost-opensource/als#17]
测速建议两种模式，单线程和多线程，这样大家就能更真实的了解网络水平

**Comment by samlm0** [comment]
> 测速建议两种模式，单线程和多线程，这样大家就能更真实的了解网络水平

直接下载静态文件即可，但是目前的浏览器大部分打开了多线程下载。

专业测速请使用 iperf

**Comment by ZealousLyon** [comment]
> 

请问静态文件下载能否使用相对路径呢，现在无论是否改端口，静态文件的下载链接均为80端口，类似`IP/文件路径`

**Comment by samlm0** [comment]
> > 
> 
> 请问静态文件下载能否使用相对路径呢，现在无论是否改端口，静态文件的下载链接均为80端口，类似`IP/文件路径`

请新开 issue, 不是同一个问题.

谢谢

**Comment by qian9008** [comment]
这个建议好
