### ISSUE TITLE
[BUG] nginx反代到子目录，网页不显示内容

### ISSUE THREAD

**Issue by niclau** [wikihost-opensource/als#44]
容器采用bridge网络，把80端口映影到宿主机的81端口
nginx配置如下：
location /lg/ {
        proxy_pass http://127.0.0.1:81;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_http_version 1.1;
}
在浏览器访问https://domain.com/lg/，页面为空白；如把location /lg/改为location /则正常显示。
![Snipaste_2023-06-21_16-46-18](https://github.com/wikihost-opensource/als/assets/575928/9ed976fe-5973-46c6-b937-e513e5645366)

# 环境
操作系统 & Docker 版本 (`lsb_release -a` && `docker version`):
Ubuntu 22.04.2 LTS ARM
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:53 2023
 OS/Arch:           linux/arm64
 Context:           default

使用的镜像版本 (`docker ps | grep als`):
9934e0c29cd0   wikihostinc/looking-glass-server:latest   "/bin/sh -c 'php81 /…"   22 minutes ago   Up 22 minutes   127.0.0.1:81->80/tcp

# 现象
预期返回: 正常访问looking glass页面

实际返回: 空白页

**Comment by samlm0** [comment]
已在 dd8705c 修复
