### ISSUE TITLE
[疑问] 容器创建1G的文件在哪里，需要认为清理么

### ISSUE THREAD

**Issue by toyo2333** [wikihost-opensource/als#46]
小白提问，容器创建测速文件1G文件放在了哪里呢？ 我stop之后还在么？我rm掉容器后 这些测速我呢见还在么？

请指教

**Comment by samlm0** [comment]
容器创建时自动生成 

生成代码可见 https://github.com/wikihost-opensource/als/blob/master/backend/app/components/10-speedtest_static.php#L15

**Comment by toyo2333** [comment]
> 容器创建时自动生成
> 
> 生成代码可见 https://github.com/wikihost-opensource/als/blob/master/backend/app/components/10-speedtest_static.php#L15

我在vps上没有找到这个文件夹啊？/app/webspaces/speedtest-static/

请问如何清理这些测速文件呢？

**Comment by toyo2333** [comment]
知道了，不需要清理，在容器文件里。rm掉之后就没有了
