### ISSUE TITLE
[BUG] 文件下载测试地址问题

### ISSUE THREAD

**Issue by yaoyao-moe** [wikihost-opensource/als#51]
# BUG 简短描述

页面中 `IPv4 下载测试` `IPv6 下载测试`实际都为访问的地址（域名），并没有分离 IPv4 和 IPv6。
这个问题应该是解决 [Issues #33](https://github.com/wikihost-opensource/als/issues/33) 的时候改的（）

# 环境
## 操作系统 & Docker 版本 (`lsb_release -a` && `docker version`):

Ubuntu 22.04.3 LTS, Docker CE 24.0.6

## 使用的镜像版本 (`docker ps | grep als`):

latest

# 现象
预期返回:
```
ipv4按钮 "IPV4_ADDR_OR_DOMAIN/speedtest-static/1MB.test"
ipv6按钮 "IPV6_ADDR_OR_DOMAIN/speedtest-static/1MB.test"
```
实际返回:
```
ipv4按钮  href="./speedtest-static/1MB.test"
ipv6按钮  href="./speedtest-static/1MB.test"
```

# 建议

`ui/src/components/Speedtest.vue` 中，使用`componentConfig.public_ipv4` / `componentConfig.public_ipv6` 构造按钮，但是可能涉及使用域名的问题，如果可以，追加 `IPV4_DOMAIN`, `IPV6_DOMAIN`相关可选配置最好。

**Comment by samlm0** [comment]
已经修复, 参见

https://github.com/wikihost-opensource/als/blob/master/ui/src/components/Speedtest/FileSpeedtest.vue#L9-L31
