### ISSUE TITLE
测速只会一直转圈圈！

### ISSUE THREAD

**Issue by yqk100** [wikihost-opensource/als#59]
项目里给的演示地址也一样，测速只会一直转圈圈。
![Screenshot_2024-01-15-23-21-25-83_a87fd7db6caa850b517aa6fa9d2fcd0e](https://github.com/wikihost-opensource/als/assets/13610251/33fc8aa9-b114-4f6d-9cde-7f329e814e7d)

**Comment by samlm0** [comment]
已在 f48e2aa85a3a607affe2c1e263483feed4e80259 修复
