### ISSUE TITLE
欧洲地区的服务器无法使用speedtest.net

### ISSUE THREAD

**Issue by rf11291** [wikihost-opensource/als#62]
目前手中的德国,英国,荷兰,卢森堡地区的服务器均无法使用speedtest.net这个功能，其他地区正常使用

**Comment by samlm0** [comment]
需要更多信息，例如截图，或者 ALS 的访问地址

**Comment by rf11291** [comment]
> 需要更多信息，例如截图，或者 ALS 的访问地址

卢森堡 http://107.189.14.228:888/
德国 http://5.252.225.114:888/

**Comment by samlm0** [comment]
我在 Shell 界面下跑了一下 speedtest, 然后两边都可以了

speedtest.net 需要同意服务协议后才能使用，晚点看看怎么处理

**Comment by rf11291** [comment]
> 我在 Shell 界面下跑了一下 speedtest， 然后两边都可以了
> 
> speedtest.net 需要同意服务协议后才能使用，晚点看看怎么处理

感谢作者维护！
