### ISSUE TITLE
可否定制部分内容

### ISSUE THREAD

**Issue by Netflixxp** [wikihost-opensource/als#7]
感谢作者的回复，我也在TG频道做了推广 https://t.me/mffjc/1035
群友希望能有一些自主修改的地方
例如
服务器提供商
谁资助的测试节点
同时，希望有个交流的地方例如， tg组啥的

**Comment by samlm0** [comment]
已加入 TODO

WIKIHOST Opensouce 没有交流群
WIKIHOST 有: https://t.me/network50_chat

**Comment by Netflixxp** [comment]
> 已加入 TODO
> 
> WIKIHOST Opensouce 没有交流群 WIKIHOST 有: https://t.me/network50_chat

这个 todo 咋用呢

**Comment by samlm0** [comment]
> > 已加入 TODO
> > WIKIHOST Opensouce 没有交流群 WIKIHOST 有: https://t.me/network50_chat
> 
> 这个 todo 咋用呢

TODO 是待办事项
